### ISSUE TITLE
na_ontap_command should support interactive commands

### ISSUE THREAD

**Issue by mamoep** [ansible-collections/netapp#27]
##### SUMMARY
na_ontap_command should support answering of interactive commands, similar to the prompt/answer options in [cli_command](https://docs.ansible.com/ansible/latest/modules/cli_command_module.html) module for network devices.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
na_ontap_command module

##### ADDITIONAL INFORMATION
There are ONTAP commands that always prompt for input, example: "system configuration backup settings set-password"

**Comment by chjones45** [comment]
+1 for this feature, for this exact use case of the system configuration backups when using the "system configuration backup settings set-password" command.

**Comment by carchi8py** [comment]
We have a new module in last month release that should be able to handle zapi calls where you need to provide an answer. 
https://github.com/ansible-collections/netapp/blob/master/ansible_collections/netapp/ontap/plugins/modules/na_ontap_zapit.py

**Comment by chjones45** [comment]
I just got it working using the zapit module. Here is the playbook tasks I've used to set the configuration backups:

```
- name: Configure Cluster Configuration Backups
  netapp.ontap.na_ontap_command:
    <<: *clusterlogin
    command: ['system configuration backup settings modify -destination {{ config_backup_url }} -username {{ config_backup_user }} -numbackups1 2 -numbackups2 2 -numbackups3 2']
    privilege: advanced
  tags: config_backups

- name: Set Cluster Configuration Backup Password
  netapp.ontap.na_ontap_zapit:
    <<: *clusterlogin
    zapi:
      config-backup-settings-password-set:
        password-for-destination-url: "{{ config_backup_password }}"
  tags: config_backup_password
```
