### ISSUE TITLE
VLAN step crashes when following docs

### ISSUE THREAD

**Issue by stobias123** [ansible-collections/netapp#33]
Minor type-o fix.

##### SUMMARY
Docs show
```
vlans:
  - { id: 201, node: cluster-01, parent: a0a }
```

Step in module doesn't reference `item.parent.`

```yaml
- name: Create VLAN
  na_ontap_net_vlan:
    state: present
    vlanid: "{{ item.id }}"
    node: "{{ item.node }}"
    parent_interface: "{{ item.port }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
role `na_ontap_cluster_config`

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
n/a
```

##### OS / ENVIRONMENT

n/a

##### STEPS TO REPRODUCE

Just run via the docs :p 

```yaml
- name: Create VLAN
  na_ontap_net_vlan:
    state: present
    vlanid: "{{ item.id }}"
    node: "{{ item.node }}"
    parent_interface: "{{ item.port }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
```

##### EXPECTED RESULTS

It to run.

##### ACTUAL RESULTS

Error.

```paste below

```
