### ISSUE TITLE
Description and default interval value issues with SolidFire snapshot schedule module

### ISSUE THREAD

**Issue by scaleoutsean** [ansible-collections/netapp#44]
##### SUMMARY

1) The module description is completely wrong (maybe not just this module).
It says it's for [account management ](https://github.com/ansible-collections/netapp/blob/ba448fe9dbbe7e9c53493a0114f66f410659dd91/ansible_collections/netapp/elementsw/plugins/modules/na_elementsw_snapshot_schedule.py#L26).

2) There's an unnecessary [default non-zero value](https://github.com/ansible-collections/netapp/blob/ba448fe9dbbe7e9c53493a0114f66f410659dd91/ansible_collections/netapp/elementsw/plugins/modules/na_elementsw_snapshot_schedule.py#L213) for `time_interval_days`. 

```
    schedule_type:
        description:
        - Schedule type for creating schedule.
        choices: ['DaysOfWeekFrequency','DaysOfMonthFrequency','TimeIntervalFrequency']

    time_interval_days:
        description: Time interval in days.
        default: 1
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

* [na_elementsw_snapshot_schedule.py](https://github.com/ansible-collections/netapp/blob/ba448fe9dbbe7e9c53493a0114f66f410659dd91/ansible_collections/netapp/elementsw/plugins/modules/na_elementsw_snapshot_schedule.py)

##### ANSIBLE VERSION

```shell
ansible 2.9.10
  config file = None
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/.local/lib/python3.6/site-packages/ansible
  executable location = /home/vagrant/.local/bin/ansible
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
```

##### CONFIGURATION

* Element OS 11.7

##### EXPECTED RESULTS

* The module description correctly describes its purpose
* The module does not use unreasonable default values

##### ACTUAL RESULTS

* The module description is wrong
* At least one variable has an unreasonable defaults value (`time_interval_days=1`). Actually I don't even understand why `time_interval_days` is necessary in the first place (there's DaysOfWeekFrequency and DaysOfMonthFrequency as well as `time_interval_hours=24`) but if it can't be removed, then it should have a reasonable default value like the other two time intervals, namely `0`.
