### ISSUE TITLE
soft limit not part of the na_ontap_quotas module

### ISSUE THREAD

**Issue by Diddi474** [ansible-collections/netapp#53]
##### ISSUE TYPE
- quota soft limit is not part of the na_ontap_quotas module we would like to set soft limit for the quotas

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by Diddi474** [comment]
thank you carchi8py we see that in api call in ontap version 9.7

**Comment by lonico** [comment]
can you clarify this request?   We already have

```
  soft_file_limit:
    description:
    - The number of files the target would have to exceed before a message is logged and an SNMP trap is generated.
    type: str
  soft_disk_limit:
    description:
    - The amount of disk space the target would have to exceed before a message is logged and an SNMP trap is generated.
    type: str
```
