### ISSUE TITLE
na_ontap_user idempotency issue with domain users

### ISSUE THREAD

**Issue by mamoep** [ansible-collections/netapp#54]
##### SUMMARY

Using na_ontap_user to create a domain user works. Running playbook again (while the user already exists) fails with: 
_An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NaApiError: NetApp API failed. Reason - 16034:User not found_
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

na_ontap_user
##### ANSIBLE VERSION

```paste below
2.9.10
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL 7.8
ONTAP 9.6P7

##### STEPS TO REPRODUCE

Run the following play twice.

```yaml
    na_ontap_user:
      state: present
      vserver: clustername
      name: DOMAIN\usergroup
      lock_user: no
      authentication_method: domain
      applications: http,ontapi,ssh
      role_name: admin
      hostname: "{{ cluster }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
```

##### EXPECTED RESULTS

ok on second run

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_na_ontap_user_payload_9Ab18t/ansible_na_ontap_user_payload.zip/ansible/modules/storage/netapp/na_ontap_user.py", line 258, in unlock_given_user
  File "/usr/lib/python2.7/site-packages/netapp_lib/api/zapi/zapi.py", line 301, in invoke_successfully
    raise NaApiError(code, msg)
NaApiError: NetApp API failed. Reason - 16034:User not found
failed: [localhost] (item=clustername) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "applications": [
                "http",
                "ontapi",
                "ssh"
            ],
            "authentication_method": "domain",
            "hostname": "clustername",
            "http_port": null,
            "https": true,
            "lock_user": false,
            "name": "DOMAIN\\usergroup",
            "ontapi": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "role_name": "admin",
            "set_password": null,
            "state": "present",
            "use_rest": "Auto",
            "username": "DOMAIN\\user",
            "validate_certs": true,
            "vserver": "clustername"
        }
    },
    "item": "clustername",
    "msg": "Error unlocking user DOMAIN\\usergroup: NetApp API failed. Reason - 16034:User not found"
}
```
