### ISSUE TITLE
How to create Cluster Peer SVM DR Permissions?

### ISSUE THREAD

**Issue by kvegh** [ansible-collections/netapp#60]
##### SUMMARY

I am running OnTap 9.7. 
Also am running ansible 2.9. 

Have set up two netapp nodes, both got a single-node-cluster configuration. 
With Ansible I can set up the SVMs. 
I also can set up the cluster Peers. 
But if I want to set up an SVM DR, I need to set the Cluster Peer SVM Permissions. 
Not sure where to do that with ansible. Is this explained in the documentation? Can't find it...

I am using the netapp.ontap.na_ontap_cluster_peer modules and the netapp.ontap.na_ontap_svm modules. 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

netapp.ontap.na_ontap_cluster_peer
and/or
netapp.ontap.na_ontap_svm

##### ANSIBLE VERSION

```paste below
[ansible@automata ~]$ ansible --version 
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
[ansible@automata ~]$ 


```

**Comment by zeten30** [comment]
Hi, maybe you're looking for na_ontap_vserver_peer.

```
EXAMPLES:

- name: Source vserver peer create
      na_ontap_vserver_peer:
        state: present
        peer_vserver: ansible2
        peer_cluster: ansibleCluster
        vserver: ansible
        applications: ['snapmirror']
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        dest_hostname: "{{ netapp_dest_hostname }}"
```
