### ISSUE TITLE
na_ontap_software_update idempotency

### ISSUE THREAD

**Issue by mamoep** [ansible-collections/netapp#61]
##### SUMMARY

na_ontap_software_update runs when package_version is the currently running version.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

na_ontap_software_update

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /ansible/private/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL 7.8
ONTAP 9.7P7
netapp.ontap collection version 20.9.0

##### STEPS TO REPRODUCE

```yaml
- hosts: NetApp_Setup
  become: false
  collections:
    - netapp.ontap
  gather_facts: false
  vars:
    login: &login
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  tasks:
   - na_ontap_software_update:
      state: present
      package_version: "{{ version }}"
      package_url: https://webserver/ontap/{{ version | replace('.', '') }}_q_image.tgz
      download_only: false
      ignore_validation_warning: true
      hostname: "{{ inventory_hostname }}"
      <<: *login
    connection: local

```

##### EXPECTED RESULTS

Return "ok" and skip update because version is already installed.

##### ACTUAL RESULTS

Update was triggered.

na_ontap_info result for the installed release:
```
    "ontap_info": {
        "ontapi_version": "170",
        "ontap_version": "170",
        "ontap_system_version": {
            "is_clustered": "true",
            "version_tuple": {
                "system_version_tuple": {
                    "generation": "9",
                    "major": "7",
                    "minor": "0"
                }
            },
            "version": "NetApp Release 9.7P7: Thu Aug 27 20:57:05 UTC 2020",
            "build_timestamp": "1598561825"
        }
    }
```

```paste below

```
